services:
  stellar-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    # Map the local 'models' folder to the container's 'models' folder
    volumes:
      - ./models:/app/models

  stellar-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://stellar-backend:5000/predict
    depends_on:
      - stellar-backend 