FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the folders and files
COPY src ./src
COPY models ./models

# ensure code knows where to find model files inside container
ENV MODEL_DIR=/app/models

COPY app.py .

EXPOSE 5000
CMD ["python", "app.py"]